{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
#  name: {{ template "fullname" . }}
  name: monasca-grafana-pvclaim
  namespace: "{{ .Values.namespace }}"
  labels:
    system: openstack
    component: monitoring

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi           # datalogs per day allocate 1-10 Gi storage on staging
{{- end }}
