---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-etc
  labels:
    system: openstack
    service: monitoring
    component: configuration

data:
  monasca-grafana.ini: |
{{ include "monasca_grafana_ini" . | indent 4 }}

