---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-bin
  labels:
    system: openstack
    service: monitoring
    component: configuration

data:
  common.sh: |
{{ .Files.Get "files/common.sh" | indent 4 }}
  common-start: |
{{ include "common_start" . | indent 4 }}
  grafana-start: |
{{ include "grafana_start" . | indent 4 }}



