apiVersion: v1
kind: Service
metadata:
  name: monasca-grafana
  namespace: "{{ .Values.namespace }}"
  labels:
    system: openstack
    service: monitoring
    component: grafana
spec:
  clusterIP: None
  selector:
    component: grafana
  ports:
    - port: {{.Values.monasca.grafana.port.public}}
