# Default values for sentry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
serverReplicaCount: 1
workerReplicaCount: 1

#  SENTRY_FILESTORE_DIR
#
#secretKey: $(docker run --rm sentry config generate-secret-key)
#emailHost:
#serverEmail: '"Sentry" <root@localhost>'
#singleOrganization: false
#githubAppId:
#githubApiSecret:
#useSsl: false
#
#extraEnvVars:
#  e.g.
#  GITHUB_BASE_DOMAIN: github.example.com
#  GITHUB_API_DOMAIN: api.github.example.com
#
image:
  repository: sentry
  tag: 8.10.0
  pullPolicy: IfNotPresent
service:
  name: sentry
  type: ClusterIP
  externalPort: 80
  internalPort: 9000

ingress:
  enabled: false
#  host:
#  tls_crt:
#  tls_key:

postgresql:
  #postgresPassword:
  postgresDatabase: sentry
  persistence:
    enabled: true
    accessMode: ReadWriteMany
    size: 10Gi
  resources:
    requests:
      memory: 10Gi
      cpu: 4
  backup:
    enabled: false
    repository: sapcc/backup-tools
    image_version: v0.4.6
    interval_full: 3 days
    interval_incr: 3 days
    os_auth_url: DEFINED-IN-REGION-SECRETS
    os_auth_version: DEFINED-IN-REGION-SECRETS
    os_identity_api_version: DEFINED-IN-REGION-SECRETS
    os_username: DEFINED-IN-REGION-SECRETS
    os_user_domain: DEFINED-IN-REGION-SECRETS
    os_project_name: DEFINED-IN-REGION-SECRETS
    os_project_domain: DEFINED-IN-REGION-SECRETS
    os_region_name: DEFINED-IN-REGION-SECRETS
    os_password: DEFINED-IN-REGION-SECRETS

redis:
  # redisPassword:
  persistence:
    enabled: true
    accessMode: ReadWriteMany
    size: 10Gi
  resources:
    requests:
      memory: 10Gi
      cpu: 2
