# Default values for elektra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replica_count: 2
image:
  repository: sapcc/elektra
  tag: latest
  pullPolicy: IfNotPresent

rails_env: production
has_keystone_router: 1
#monsoon_dashboard_region: staging
#monsoon_dashboard_landscape: staging
monsoon_dashboard_mail_server: mail.sap.corp
monsoon_dashboard_avatar_url: https://avatars.wdf.sap.corp/avatar/#{current_user.name}?size=24x24
#monsoon_openstack_auth_api_endpoint:
monsoon_openstack_auth_api_userid: dashboard
monsoon_openstack_auth_api_domain: Default
swift_reselleradmin_project: service
swift_reselleradmin_role: swiftreseller
swift_reselleradmin_project_domain: Default
#swift_reselleradmin_region: staging
#arc_updates_url:
#arc_pki_url:
#arc_broker_url:

#monsoon_openstack_auth_api_password:
#monsoon_rails_secret_token:
#sentry_dsn:
ingress:
  enabled: false
#  host: dashboard.staging.cloud.sap
#  tls_crt:
#  tls_key:

postgres:
  persistence:
    enabled: true
  name: elektra
#   password:
  backup:
    enabled: false
    repository: sapcc/backup-tools
    image_version: v0.4.1
    interval_full: 3 days
    interval_incr: 3 days
    os_auth_url: DEFINED-IN-REGION-SECRETS
    os_auth_version: DEFINED-IN-REGION-SECRETS
    os_identity_api_version: DEFINED-IN-REGION-SECRETS
    os_username: DEFINED-IN-REGION-SECRETS
    os_user_domain: DEFINED-IN-REGION-SECRETS
    os_project_name: DEFINED-IN-REGION-SECRETS
    os_project_domain: DEFINED-IN-REGION-SECRETS
    os_region_name: DEFINED-IN-REGION-SECRETS
    os_password: DEFINED-IN-REGION-SECRETS

