## postgres image version
## ref: https://hub.docker.com/r/library/postgres/tags/
##
image: "postgres"
imageTag: "9.5.4"

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

## Create a database user
## Default: postgres
# postgresUser:
## Default: random 10 character string
# postgresPassword:

## Create a database
## Default: the postgres user
# postgresDatabase:

## Persist data to a persitent volume
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi

metrics:
  enabled: false
  image: wrouesnel/postgres_exporter:v0.1.1
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m

backup:
  enabled: false
  repository: sapcc/backup-tools
  image_version: v0.4.6
  interval_full: 3 days
  interval_incr: 3 days
  os_auth_url: DEFINED-IN-REGION-SECRETS
  os_auth_version: DEFINED-IN-REGION-SECRETS
  os_identity_api_version: DEFINED-IN-REGION-SECRETS
  os_username: DEFINED-IN-REGION-SECRETS
  os_user_domain: DEFINED-IN-REGION-SECRETS
  os_project_name: DEFINED-IN-REGION-SECRETS
  os_project_domain: DEFINED-IN-REGION-SECRETS
  os_region_name: DEFINED-IN-REGION-SECRETS
  os_password: DEFINED-IN-REGION-SECRETS